# Generated by Django 2.1.dev20180110171304 on 2018-01-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_list', models.CharField(max_length=40)),
                ('date_of_creation', models.DateTimeField(verbose_name='date of creation')),
                ('date_of_obsolescence', models.DateTimeField(verbose_name='date of obsolescence')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageLists.Checklist')),
            ],
        ),
    ]
