# Generated by Django 2.1.dev20180110171304 on 2018-01-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageLists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='name_of_list',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='name_of_item',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='date_of_obsolescence',
        ),
    ]
